### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jackparmer**

### CODE REVIEW

**Comment by jackparmer** [comment]
pls review @JeffDotPng or @itsjoeoui !

**Review by JeffDotPng — APPROVED** [review]
LGTM, however I'm noticing a lot of hard coded styles (hex/rgb values for colors) in some of these files, we could benefit a lot from making a Mantine theme object to keep everything consistent and make the code a lot cleaner. Should probably make an issue for that.

**Comment by itsjoeoui** [comment]
> pls review @JeffDotPng or @itsjoeoui !

LGTM!

**Review by itsjoeoui — APPROVED** [review]

**Comment by itsjoeoui** [comment]
> LGTM, however I'm noticing a lot of hard coded styles (hex/rgb values for colors) in some of these files, we could benefit a lot from making a Mantine theme object to keep everything consistent and make the code a lot cleaner. Should probably make an issue for that.

Done 👍

**Review by itsjoeoui — APPROVED** [review]
lgtm

**Pull request merged**
